/*==============================================================================
                    Part 1 : Introduction
==============================================================================*/

USE RetailSalesDB;
GO

PRINT '==============================================================';
PRINT 'Retail Sales Analytics & Inventory Management System';
PRINT '23_Executive_KPIs.sql';
PRINT '==============================================================';

/*
==============================================================================
Script Name
==============================================================================
23_Executive_KPIs.sql

==============================================================================
Purpose
==============================================================================
This script presents an executive-level overview of the retail business
through Key Performance Indicators (KPIs). It summarizes the most
important business metrics required by senior management for strategic
decision-making.

==============================================================================
Target Audience
==============================================================================
• Chief Executive Officer (CEO)
• Chief Financial Officer (CFO)
• Chief Operating Officer (COO)
• Business Managers
• Sales Managers
• Business Analysts

==============================================================================
Business Objectives
==============================================================================
• Monitor overall business performance.
• Measure revenue and sales performance.
• Evaluate customer growth and engagement.
• Analyze product performance.
• Monitor inventory health.
• Track payment and return trends.
• Evaluate employee performance.
• Support executive decision-making.

==============================================================================
KPI Numbering Standard
==============================================================================
This project follows a Global KPI Numbering System.

Example:

KPI 001 : Business Overview
KPI 002 : Total Net Revenue
KPI 003 : Average Order Value
...
KPI 999 : Final Business KPI

KPI numbers never restart across different SQL scripts.

==============================================================================
Business Areas Covered
==============================================================================

Part 2  : Business Overview

Part 3  : Revenue KPIs

Part 4  : Order KPIs

Part 5  : Customer KPIs

Part 6  : Product KPIs

Part 7  : Inventory KPIs

Part 8  : Return KPIs

Part 9  : Payment KPIs

Part 10 : Employee KPIs

Part 11 : Executive Scorecard

Part 12 : Completion

==============================================================================
Output
==============================================================================
The output generated by this script serves as the primary data source
for the Executive Dashboard in Power BI.

Each KPI can be exported as:

• CSV
• Screenshot
• Power BI Card
• Executive Report

==============================================================================
Author
==============================================================================
Akshay Aswani

==============================================================================
Project
==============================================================================
Retail Sales Analytics & Inventory Management System

==============================================================================
*/

PRINT 'Starting Executive KPI Analysis...';
PRINT '==============================================================';
GO

/*==============================================================================
                    Part 2 : Business Overview
==============================================================================*/

PRINT '==============================================================';
PRINT 'Part 2 : Business Overview';
PRINT '==============================================================';

/*------------------------------------------------------------------------------
KPI 001 : Business Overview
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the current size and operational footprint of the business?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Provides an executive summary of the business by reporting the total
number of customers, stores, products, suppliers, employees, orders,
payments, returns and inventory records.

This KPI serves as the foundation for understanding overall business
scale before reviewing detailed performance metrics.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

A single-row summary showing the overall size of the business across
all major entities.

------------------------------------------------------------------------------*/

SELECT

    DB_NAME() AS DatabaseName,

    (
        SELECT COUNT(*)
        FROM dbo.Customer
    ) AS TotalCustomers,

    (
        SELECT COUNT(*)
        FROM dbo.Store
    ) AS TotalStores,

    (
        SELECT COUNT(*)
        FROM dbo.Product
    ) AS TotalProducts,

    (
        SELECT COUNT(*)
        FROM dbo.Supplier
    ) AS TotalSuppliers,

    (
        SELECT COUNT(*)
        FROM dbo.Employee
    ) AS TotalEmployees,

    (
        SELECT COUNT(*)
        FROM dbo.[Order]
    ) AS TotalOrders,

    (
        SELECT COUNT(*)
        FROM dbo.OrderItem
    ) AS TotalOrderItems,

    (
        SELECT COUNT(*)
        FROM dbo.Payment
    ) AS TotalPayments,

    (
        SELECT COUNT(*)
        FROM dbo.[Return]
    ) AS TotalReturns,

    (
        SELECT COUNT(*)
        FROM dbo.Inventory
    ) AS InventoryRecords;

PRINT 'KPI 001 : Business Overview Generated Successfully.';
PRINT '==============================================================';
GO

/*==============================================================================
                    Part 3 : Revenue KPIs
==============================================================================*/

PRINT '==============================================================';
PRINT 'Part 3 : Revenue KPIs';
PRINT '==============================================================';


/*------------------------------------------------------------------------------
KPI 002 : Total Net Revenue
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the total net revenue generated by the business?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Total Net Revenue is the most important financial KPI. It represents
the total income generated after applying discounts and taxes.

This KPI provides executives with a quick overview of the company's
overall sales performance.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Higher revenue indicates stronger business growth and better sales
performance.

------------------------------------------------------------------------------*/

SELECT

    SUM(NetAmount) AS TotalNetRevenue

FROM dbo.[Order];

PRINT 'KPI 002 : Total Net Revenue Generated Successfully.';
PRINT '--------------------------------------------------------------';

/*------------------------------------------------------------------------------
KPI 003 : Average Order Value (AOV)
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the average value of each customer order?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Average Order Value (AOV) measures customer spending behavior and
helps evaluate pricing strategies, upselling opportunities, and
overall customer purchasing habits.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

A higher Average Order Value generally indicates that customers are
purchasing more products or higher-value products per transaction.

------------------------------------------------------------------------------
*/

SELECT

    CAST(AVG(NetAmount) AS DECIMAL(12,2)) AS AverageOrderValue

FROM dbo.[Order];

PRINT 'KPI 003 : Average Order Value Generated Successfully.';
PRINT '--------------------------------------------------------------';

/*------------------------------------------------------------------------------
KPI 004 : Highest Order Value
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the highest order value recorded?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Identifies the largest customer purchase and helps understand
high-value sales transactions.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the maximum revenue generated from a single order.

------------------------------------------------------------------------------
*/

SELECT

    MAX(NetAmount) AS HighestOrderValue

FROM dbo.[Order];

PRINT 'KPI 004 : Highest Order Value Generated Successfully.';
PRINT '--------------------------------------------------------------';



/*------------------------------------------------------------------------------
KPI 005 : Lowest Order Value
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the lowest order value recorded?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Helps identify the smallest customer purchases and evaluate minimum
transaction values.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the minimum revenue generated from a single order.

------------------------------------------------------------------------------
*/

SELECT

    MIN(NetAmount) AS LowestOrderValue

FROM dbo.[Order];

PRINT 'KPI 005 : Lowest Order Value Generated Successfully.';
PRINT '--------------------------------------------------------------';



/*------------------------------------------------------------------------------
KPI 006 : Revenue Per Customer
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

On average, how much revenue is generated from each customer?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Revenue Per Customer measures customer value and helps evaluate
customer profitability.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Higher revenue per customer indicates stronger customer value and
better purchasing behavior.

------------------------------------------------------------------------------
*/

SELECT

    CAST
    (
        SUM(NetAmount) /
        NULLIF(COUNT(DISTINCT CustomerID),0)
        AS DECIMAL(12,2)
    ) AS RevenuePerCustomer

FROM dbo.[Order];

PRINT 'KPI 006 : Revenue Per Customer Generated Successfully.';
PRINT '--------------------------------------------------------------';



/*------------------------------------------------------------------------------
KPI 007 : Total Discount Given
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How much discount has been provided to customers?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Discounts are used to attract customers and increase sales.
Monitoring discounts helps management balance revenue growth with
profitability.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the total discount amount offered across all orders.

------------------------------------------------------------------------------
*/

SELECT

    SUM(DiscountAmount) AS TotalDiscountGiven

FROM dbo.[Order];

PRINT 'KPI 007 : Total Discount Given Generated Successfully.';
PRINT '--------------------------------------------------------------';



/*------------------------------------------------------------------------------
KPI 008 : Total Tax Collected
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How much tax has been collected from customer orders?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Tax collection is an important financial metric for regulatory
compliance and financial reporting.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the total tax collected across all customer transactions.

------------------------------------------------------------------------------
*/

SELECT

    SUM(TaxAmount) AS TotalTaxCollected

FROM dbo.[Order];

PRINT 'KPI 008 : Total Tax Collected Generated Successfully.';
PRINT '==============================================================';
GO

/*==============================================================================
                    Part 4 : Order KPIs
==============================================================================*/

PRINT '==============================================================';
PRINT 'Part 4 : Order KPIs';
PRINT '==============================================================';



/*------------------------------------------------------------------------------
KPI 009 : Total Orders
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many customer orders have been placed?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Total Orders is one of the primary operational KPIs. It reflects overall
business activity and customer demand.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

A higher number of orders generally indicates increased customer
engagement and business growth.

------------------------------------------------------------------------------
*/

SELECT

    COUNT(*) AS [Total Orders]

FROM dbo.[Order];

PRINT 'KPI 009 : Total Orders Generated Successfully.';
PRINT '--------------------------------------------------------------';



/*------------------------------------------------------------------------------
KPI 010 : Orders by Status
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many orders belong to each order status?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Tracking orders by status helps management monitor order fulfillment,
pending orders, completed orders, cancelled orders and operational
efficiency.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Provides a complete breakdown of all orders by their current status.

------------------------------------------------------------------------------
*/

SELECT

    OS.StatusName AS [Order Status],
    COUNT(O.OrderID)   AS [Total Orders]

FROM dbo.[Order] O

INNER JOIN dbo.OrderStatus OS
    ON O.OrderStatusID = OS.OrderStatusID

GROUP BY

    OS.StatusName

ORDER BY

    [Total Orders] DESC;

PRINT 'KPI 010 : Orders by Status Generated Successfully.';
PRINT '--------------------------------------------------------------';


/*------------------------------------------------------------------------------
KPI 011 : Average Items Per Order
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

On average, how many products are purchased in each customer order?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Average Items Per Order measures customer purchasing behavior and helps
evaluate cross-selling, up-selling, and basket size.

A higher average indicates that customers are buying more products in
each transaction.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the average number of items purchased per order across the business.

------------------------------------------------------------------------------
*/

SELECT

    CAST(AVG(OrderItemCount) AS DECIMAL(10,2)) AS [Average Items Per Order]

FROM
(
    SELECT

        OrderID,
        SUM(Quantity) AS OrderItemCount

    FROM dbo.OrderItem

    GROUP BY

        OrderID

) AS OrderSummary;

PRINT 'KPI 011 : Average Items Per Order Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 012 : Average Daily Orders
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

On average, how many customer orders are placed each day?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Average Daily Orders measures the business's daily operational volume
and helps management understand customer demand patterns.

This KPI is useful for workforce planning, inventory replenishment,
and sales forecasting.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Shows the average number of customer orders placed per business day.

------------------------------------------------------------------------------
*/

SELECT

    CAST
    (
        COUNT(OrderID) * 1.0 /
        COUNT(DISTINCT CAST(OrderDate AS DATE))
        AS DECIMAL(10,2)
    ) AS [Average Daily Orders]

FROM dbo.[Order];

PRINT 'KPI 012 : Average Daily Orders Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 013 : Highest Items in a Single Order
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customer order contains the highest number of items purchased?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Identifying the largest order helps the business understand peak
customer purchasing behavior and evaluate opportunities for bulk sales,
promotional campaigns, and inventory planning.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the order with the highest total quantity of items purchased,
along with the customer, order date, and total order value.

------------------------------------------------------------------------------
*/

SELECT TOP (1)

    O.OrderNumber                          AS [Order Number],
    C.FirstName							   AS [First Name],
	C.LastName							   As [Last Name],
    CAST(O.OrderDate AS DATE)              AS [Order Date],
    SUM(OI.Quantity)                       AS [Total Items Purchased],
    O.NetAmount                            AS [Order Value]

FROM dbo.[Order] O

INNER JOIN dbo.Customer C
    ON O.CustomerID = C.CustomerID

INNER JOIN dbo.OrderItem OI
    ON O.OrderID = OI.OrderID

GROUP BY

    O.OrderNumber,
    C.FirstName,
	C.LastName,
    O.OrderDate,
    O.NetAmount

ORDER BY

    [Total Items Purchased] DESC,
    [Order Value] DESC;

PRINT 'KPI 013 : Highest Items in a Single Order Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 014 : Lowest Items in a Single Order
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customer order contains the lowest number of items purchased?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Identifying the smallest customer orders helps understand low-value
purchasing behavior and provides opportunities to improve basket size
through cross-selling, promotional offers, and product bundling.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the order with the lowest total quantity of items purchased,
along with the customer, order date, and total order value.

------------------------------------------------------------------------------
*/

SELECT TOP (1)

    O.OrderNumber                     AS [Order Number],
    C.FirstName						  AS [First Name],
    CAST(O.OrderDate AS DATE)         AS [Order Date],
    SUM(OI.Quantity)                  AS [Total Items Purchased],
    O.NetAmount                       AS [Order Value]

FROM dbo.[Order] O

INNER JOIN dbo.Customer C
    ON O.CustomerID = C.CustomerID

INNER JOIN dbo.OrderItem OI
    ON O.OrderID = OI.OrderID

GROUP BY

    O.OrderNumber,
    C.FirstName,
    O.OrderDate,
    O.NetAmount

ORDER BY

    [Total Items Purchased] ASC,
    [Order Value] ASC;

PRINT 'KPI 014 : Lowest Items in a Single Order Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 015 : Orders by Store
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many customer orders has each store processed?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

This KPI helps management evaluate store performance by measuring
the number of customer orders handled by each store.

It can be used to identify high-performing stores, optimize staffing,
and support inventory planning.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of orders processed by each store,
ranked from highest to lowest.

------------------------------------------------------------------------------
*/

SELECT

    S.StoreName                     AS [Store Name],
    COUNT(O.OrderID)                AS [Total Orders]

FROM dbo.[Order] O

INNER JOIN dbo.Store S
    ON O.StoreID = S.StoreID

GROUP BY

    S.StoreName

ORDER BY

    [Total Orders] DESC;

PRINT 'KPI 015 : Orders by Store Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 016 : Orders by Employee
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many customer orders has each employee processed?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

This KPI helps evaluate employee productivity by measuring the number
of customer orders handled by each employee.

It assists management in identifying top-performing employees,
balancing workloads, and recognizing training opportunities.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of orders processed by each employee,
ranked from highest to lowest.

------------------------------------------------------------------------------
*/

SELECT

    E.EmployeeID                     AS [Employee ID],
    CONCAT(E.FirstName, ' ', E.LastName)                   AS [Employee Name],
    COUNT(O.OrderID)                 AS [Total Orders Processed]

FROM dbo.[Order] O

INNER JOIN dbo.Employee E
    ON O.EmployeeID = E.EmployeeID

GROUP BY

    E.EmployeeID,
    CONCAT(E.FirstName, ' ', E.LastName) 

ORDER BY

    [Total Orders Processed] DESC,
    [Employee Name];

PRINT 'KPI 016 : Orders by Employee Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 017 : Top 10 Highest Value Orders
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customer orders generated the highest revenue?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

High-value orders contribute significantly to overall revenue. Identifying
these orders helps management recognize premium customers, evaluate
large purchases, and develop targeted marketing strategies.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the Top 10 highest-value customer orders based on Net Amount.

------------------------------------------------------------------------------
*/

SELECT TOP (10)

    O.OrderNumber                     AS [Order Number],
    CONCAT(C.FirstName, ' ', C.LastName)                     AS [Customer Name],
    S.StoreName                       AS [Store Name],
    CONCAT(E.FirstName, ' ', E.LastName)                     AS [Processed By],
    CAST(O.OrderDate AS DATE)         AS [Order Date],
    O.NetAmount                       AS [Order Value]

FROM dbo.[Order] O

INNER JOIN dbo.Customer C
    ON O.CustomerID = C.CustomerID

INNER JOIN dbo.Store S
    ON O.StoreID = S.StoreID

INNER JOIN dbo.Employee E
    ON O.EmployeeID = E.EmployeeID

ORDER BY

    O.NetAmount DESC,
    O.OrderDate DESC;

PRINT 'KPI 017 : Top 10 Highest Value Orders Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 018 : Order Status Distribution
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the distribution of customer orders across different order
statuses?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Monitoring order status distribution helps management evaluate the
overall efficiency of the order fulfillment process.

A high percentage of completed orders indicates smooth operations,
while a high number of pending or cancelled orders may highlight
operational bottlenecks requiring attention.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the number and percentage of orders in each status, providing
an overview of the business's operational performance.

------------------------------------------------------------------------------
*/

SELECT

    OS.StatusName                           AS [Order Status],

    COUNT(O.OrderID)                             AS [Total Orders],

    CAST
    (
        COUNT(O.OrderID) * 100.0 /
        SUM(COUNT(O.OrderID)) OVER ()
        AS DECIMAL(10,2)
    )                                            AS [Order Percentage (%)]

FROM dbo.[Order] O

INNER JOIN dbo.OrderStatus OS
    ON O.OrderStatusID = OS.OrderStatusID

GROUP BY

    OS.StatusName

ORDER BY

    [Total Orders] DESC;

PRINT 'KPI 018 : Order Status Distribution Generated Successfully.';
PRINT '==============================================================';
GO

/*==============================================================================
                    Part 5 : Customer KPIs
==============================================================================*/

PRINT '==============================================================';
PRINT 'Part 5 : Customer KPIs';
PRINT '==============================================================';



/*------------------------------------------------------------------------------
KPI 019 : Total Customers
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many customers are registered in the business?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

The total number of registered customers represents the size of the
customer base and serves as a fundamental business KPI.

Monitoring customer growth helps management evaluate business expansion,
marketing effectiveness, and long-term customer acquisition.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of registered customers in the system.

------------------------------------------------------------------------------
*/

SELECT

    COUNT(CustomerID) AS [Total Customers]

FROM dbo.Customer;

PRINT 'KPI 019 : Total Customers Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 020 : Active Customers
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many customers are currently active?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Active customers represent the engaged customer base and indicate the
number of customers who are currently eligible for transactions.

Monitoring active customers helps management evaluate customer retention,
engagement, and the effectiveness of customer relationship strategies.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of active customers registered in the system.

------------------------------------------------------------------------------
*/

SELECT

    COUNT(CustomerID) AS [Active Customers]

FROM dbo.Customer

WHERE

    IsActive = 1;

PRINT 'KPI 020 : Active Customers Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 021 : Inactive Customers
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many registered customers are currently inactive?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Inactive customers represent the portion of the customer base that is
currently not engaged with the business.

Monitoring inactive customers helps management identify customer churn,
evaluate retention strategies, and plan re-engagement campaigns.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of inactive customers registered in the system.

------------------------------------------------------------------------------
*/

SELECT

    COUNT(CustomerID) AS [Inactive Customers]

FROM dbo.Customer

WHERE

    IsActive = 0;

PRINT 'KPI 021 : Inactive Customers Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 022 : New Customers
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How many new customers have registered with the business?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Tracking new customer registrations helps measure business growth,
marketing effectiveness, and customer acquisition performance.

A growing customer base indicates successful marketing campaigns and
expanding business reach.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of customers registered in each month,
allowing management to monitor customer acquisition trends over time.

------------------------------------------------------------------------------
*/

SELECT

    YEAR(RegistrationDate)                     AS [Year],

    MONTH(RegistrationDate)                    AS [Month Number],

    DATENAME(MONTH, RegistrationDate)          AS [Month],

    COUNT(CustomerID)                          AS [New Customers]

FROM dbo.Customer

GROUP BY

    YEAR(RegistrationDate),
    MONTH(RegistrationDate),
    DATENAME(MONTH, RegistrationDate)

ORDER BY

    [Year],
    [Month Number];

PRINT 'KPI 022 : New Customers Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 023 : Customers by City
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which cities have the highest number of registered customers?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Understanding customer distribution across cities helps the business
identify key markets, evaluate regional demand, and plan targeted
marketing campaigns.

It also supports business expansion and store location decisions.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of registered customers in each city,
ranked from highest to lowest.

------------------------------------------------------------------------------
*/

SELECT

    City AS [City],

    COUNT(CustomerID) AS [Total Customers]

FROM dbo.Customer

GROUP BY

    City

ORDER BY

    [Total Customers] DESC,
    City;

PRINT 'KPI 023 : Customers by City Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 024 : Customers by State
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which states have the highest number of registered customers?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Understanding customer distribution across states helps management
identify strong regional markets, evaluate business reach, and support
strategic decisions related to regional expansion, marketing campaigns,
and resource allocation.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the total number of registered customers in each state,
ranked from highest to lowest.

------------------------------------------------------------------------------
*/

SELECT

    State AS [State],

    COUNT(CustomerID) AS [Total Customers]

FROM dbo.Customer

GROUP BY

    State

ORDER BY

    [Total Customers] DESC,
    State;

PRINT 'KPI 024 : Customers by State Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 025 : Top 10 Customers by Revenue
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customers have generated the highest revenue for the business?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Identifying top revenue-generating customers helps the business
recognize its most valuable customers, strengthen customer
relationships, and design loyalty or premium membership programs.

This KPI is essential for customer retention and revenue optimization.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the Top 10 customers ranked by total revenue generated.

------------------------------------------------------------------------------
*/

SELECT TOP (10)

    C.CustomerID                                          AS [Customer ID],

    CONCAT(C.FirstName,' ',C.LastName)                    AS [Customer Name],

    COUNT(DISTINCT O.OrderID)                             AS [Total Orders],

    SUM(O.NetAmount)                                      AS [Total Revenue],

    AVG(O.NetAmount)                                      AS [Average Order Value]

FROM dbo.Customer C

INNER JOIN dbo.[Order] O
    ON C.CustomerID = O.CustomerID

GROUP BY

    C.CustomerID,
    C.FirstName,
    C.LastName

ORDER BY

    [Total Revenue] DESC,
    [Total Orders] DESC;

PRINT 'KPI 025 : Top 10 Customers by Revenue Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 026 : Top 10 Customers by Orders
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customers have placed the highest number of orders?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Identifying customers with the highest purchase frequency helps the
business understand customer loyalty and buying behavior.

Customers who purchase frequently are valuable for retention programs,
personalized marketing campaigns, and loyalty rewards.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the Top 10 customers ranked by the total number of orders
placed, along with their total revenue contribution.

------------------------------------------------------------------------------
*/

SELECT TOP (10)

    C.CustomerID                                          AS [Customer ID],

    CONCAT(C.FirstName,' ',C.LastName)                    AS [Customer Name],

    COUNT(O.OrderID)                                      AS [Total Orders],

    SUM(O.NetAmount)                                      AS [Total Revenue],

    AVG(O.NetAmount)                                      AS [Average Order Value]

FROM dbo.Customer C

INNER JOIN dbo.[Order] O
    ON C.CustomerID = O.CustomerID

GROUP BY

    C.CustomerID,
    C.FirstName,
    C.LastName

ORDER BY

    [Total Orders] DESC,
    [Total Revenue] DESC;

PRINT 'KPI 026 : Top 10 Customers by Orders Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 027 : Average Revenue per Customer
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

What is the average revenue generated per customer?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Average Revenue per Customer (ARPC) measures the average monetary value
contributed by each customer.

This KPI helps management evaluate customer profitability, pricing
strategies, and the effectiveness of customer acquisition efforts.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the average revenue generated per customer based on all
completed customer orders.

------------------------------------------------------------------------------
*/

SELECT

    CAST
    (
        SUM(O.NetAmount) * 1.0 /
        COUNT(O.CustomerID)
        AS DECIMAL(12,2)
    ) AS [Average Revenue per Customer]

FROM dbo.[Order] O;

PRINT 'KPI 027 : Average Revenue per Customer Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 028 : Loyalty Points Distribution
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

How are loyalty points distributed across registered customers?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Loyalty points indicate customer engagement and purchasing behavior.

Analyzing loyalty point distribution helps management identify highly
engaged customers, evaluate loyalty program effectiveness, and plan
reward campaigns.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the distribution of customers based on their loyalty points.

------------------------------------------------------------------------------
*/

SELECT

    CASE

        WHEN LoyaltyPoints = 0 THEN 'No Points'

        WHEN LoyaltyPoints BETWEEN 1 AND 500
            THEN '1 - 500'

        WHEN LoyaltyPoints BETWEEN 501 AND 1000
            THEN '501 - 1000'

        WHEN LoyaltyPoints BETWEEN 1001 AND 2000
            THEN '1001 - 2000'

        ELSE 'Above 2000'

    END AS [Loyalty Points Range],

    COUNT(CustomerID) AS [Total Customers]

FROM dbo.Customer

GROUP BY

    CASE

        WHEN LoyaltyPoints = 0 THEN 'No Points'

        WHEN LoyaltyPoints BETWEEN 1 AND 500
            THEN '1 - 500'

        WHEN LoyaltyPoints BETWEEN 501 AND 1000
            THEN '501 - 1000'

        WHEN LoyaltyPoints BETWEEN 1001 AND 2000
            THEN '1001 - 2000'

        ELSE 'Above 2000'

    END

ORDER BY

    MIN(LoyaltyPoints);

PRINT 'KPI 028 : Loyalty Points Distribution Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

/*------------------------------------------------------------------------------
KPI 029 : Top 10 Customers by Loyalty Points
------------------------------------------------------------------------------*/

/*
------------------------------------------------------------------------------
Business Question
------------------------------------------------------------------------------

Which customers have accumulated the highest loyalty points?

------------------------------------------------------------------------------
Business Importance
------------------------------------------------------------------------------

Customers with the highest loyalty points are typically the most
engaged and valuable customers.

Identifying these customers helps the business reward loyalty,
improve customer retention, and strengthen long-term relationships.

------------------------------------------------------------------------------
Expected Insight
------------------------------------------------------------------------------

Displays the Top 10 customers ranked by loyalty points, along with
their total orders and total revenue.

------------------------------------------------------------------------------
*/

SELECT TOP (10)

    C.CustomerID                                          AS [Customer ID],

    CONCAT(C.FirstName,' ',C.LastName)                    AS [Customer Name],

    C.LoyaltyPoints                                       AS [Loyalty Points],

    COUNT(DISTINCT O.OrderID)                             AS [Total Orders],

    ISNULL(SUM(O.NetAmount), 0)                           AS [Total Revenue]

FROM dbo.Customer C

LEFT JOIN dbo.[Order] O
       ON C.CustomerID = O.CustomerID

GROUP BY

    C.CustomerID,
    C.FirstName,
    C.LastName,
    C.LoyaltyPoints

ORDER BY

    C.LoyaltyPoints DESC,
    [Total Revenue] DESC;
    
PRINT 'KPI 029 : Top 10 Customers by Loyalty Points Generated Successfully.';
PRINT '--------------------------------------------------------------';
GO

